{"content": {"suites": {"0": {"status": {"total_pass": 3, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 1, "total_error": 0}, "tests": {"0": {"status": "FAIL", "message": "       ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)\n       urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='thetestingworldapi.com', port=443): Max retries exceeded with url: /api/studentsDetails (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)')))\n           requests.exceptions.SSLError: HTTPSConnectionPool(host='thetestingworldapi.com', port=443): Max retries exceeded with url: /api/studentsDetails (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)')))\n", "test_name": "test_add_student_data", "rerun": "0"}, "1": {"status": "PASS", "message": "", "test_name": "test_get_student_data", "rerun": "0"}, "2": {"status": "PASS", "message": "", "test_name": "test_update_student_data", "rerun": "0"}, "3": {"status": "PASS", "message": "", "test_name": "test_delete_student_data", "rerun": "0"}}, "suite_name": "PytestStudent/test_AddNewStudent.py"}}}, "date": "June 16, 2022", "start_time": 1655364703.5370243, "total_suite": 1, "status": "FAIL", "status_list": {"pass": "3", "fail": "1", "skip": "0", "error": "0", "xpass": "0", "xfail": "0", "rerun": "0"}, "total_tests": "4"}